Basic: 19                           # 基础价格
K-type:                             # 类型系数
    rare: 6.0                       # 稀有物品
    armor: 4.8                      # 盔甲
    advanced-resource: 3.2          # 高级资源
    tool-and-weapon: 2.8            # 工具与武器
K-material:                         # 材质系数
    diamond: 1.3                    # 钻石
    netherite: 1.45                 # 下界合金
K-enchantment:                      # 附魔系数
    enchanted: 1.2
rare-item:
    - ENCHANTED_GOLDEN_APPLE	# 附魔金苹果
    - TRIAL_KEY					# 试炼钥匙
    - OMINOUS_TRIAL_KEY			# 不详试炼钥匙
    - NETHER_STAR				# 下界之星
    - ELYTRA					# 鞘翅
    - HEAVY_CORE				# 沉重核心
    - HEART_OF_THE_SEA			# 海洋之心
    - NETHERITE_INGOT			# 下界合金锭
    - NETHERITE_BLOCK			# 下界合金块
    - DRAGON_EGG				# 龙蛋
    - DRAGON_HEAD				# 龙首
    - TOTEM_OF_UNDYING			# 不死图腾
    - BEACON					# 信标
advanced-resource-item:             # 高级资源
    - EXPERIENCE_BOTTLE			# 附魔之瓶
    - ENDER_EYE					# 末影之眼
    - DIAMOND_HORSE_ARMOR		# 钻石马铠
    - GOLDEN_HORSE_ARMOR		# 金马铠
    - GOAT_HORN					# 山羊角
    - RECOVERY_COMPASS			# 追溯指针
    - LADDER					# 鞍
    - DRAGON_BREATH				# 龙息
    - DIAMOND					# 钻石
    - DIAMOND_BLOCK				# 钻石块
    - DIAMOND_ORE				# 钻石矿石
    - DEEPSLATE_DIAMOND_ORE		# 深层钻石矿石
    - ANCIENT_DEBRIS			# 远古残骸
    - NETHERITE_SCRAP			# 下界合金碎片
    - DISC_FRAGMENT_5			# 唱片残片
    - SHULKER_SHELL				# 潜影壳
    - SHULKER_BOX				# 潜影盒
    - TURTLE_SCUTE				# 海龟鳞甲
    - ENCHANTING_TABLE			# 附魔台
    - ENCHANTING_TABLE			# 附魔台
    - VERDANT_FROGLIGHT			# 青翠蛙明灯
    - PEARLESCENT_FROGLIGHT		# 珠光蛙明灯
    - END_CRYSTAL				# 末影水晶
    - ECHO_SHARD				# 回响碎片
    - ENCHANTED_BOOK			# 附魔书
    - MUSIC_DISC_13				# 音乐唱片
    - MUSIC_DISC_CAT
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_CREATOR
    - MUSIC_DISC_CREATOR_MUSIC_BOX
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_PRECIPICE
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WARD
    - MUSIC_DISC_11
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_PIGSTEP
    - MUSIC_DISC_OTHERSIDE
    - MUSIC_DISC_5
    - MUSIC_DISC_RELIC
    - NETHERITE_UPGRADE_SMITHING_TEMPLATE		# 下界合金升级
    - COAST_ARMOR_TRIM_SMITHING_TEMPLATE		# 海岸盔甲纹饰
    - DUNE_ARMOR_TRIM_SMITHING_TEMPLATE			# 沙丘盔甲纹饰
    - EYE_ARMOR_TRIM_SMITHING_TEMPLATE			# 眼眸盔甲纹饰
    - HOST_ARMOR_TRIM_SMITHING_TEMPLATE			# 雇主盔甲纹饰
    - RAISER_ARMOR_TRIM_SMITHING_TEMPLATE		# 牧民盔甲纹饰
    - RIB_ARMOR_TRIM_SMITHING_TEMPLATE			# 肋骨盔甲纹饰
    - SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE		# 哨兵盔甲纹饰
    - SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE		# 塑造盔甲纹饰
    - SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE		# 幽静盔甲纹饰
    - SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE		# 猪鼻盔甲纹饰
    - SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE		# 尖塔盔甲纹饰
    - TIDE_ARMOR_TRIM_SMITHING_TEMPLATE			# 潮汐盔甲纹饰
    - VEX_ARMOR_TRIM_SMITHING_TEMPLATE			# 恼鬼盔甲纹饰
    - WARD_ARMOR_TRIM_SMITHING_TEMPLATE			# 监守盔甲纹饰
    - WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE	# 向导盔甲纹饰
    - WILD_ARMOR_TRIM_SMITHING_TEMPLATE			# 荒野盔甲纹饰
    - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE			# 涡流盔甲纹饰
    - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE			# 镶铆盔甲纹饰
    
armor-item:                                 # 盔甲
    - LEATHER_CHESTPLATE			# 皮革胸甲
    - CHAINMAIL_CHESTPLATE			# 锁链胸甲
    - IRON_CHESTPLATE				# 铁胸甲
    - DIAMOND_CHESTPLATE			# 钻石胸甲
    - GOLDEN_CHESTPLATE				# 金胸甲
    - NETHERITE_CHESTPLATE			# 下界合金胸甲
    - LEATHER_BOOTS					# 皮革靴子
    - CHAINMAIL_BOOTS				# 锁链靴子
    - IRON_BOOTS					# 铁靴子
    - DIAMOND_BOOTS					# 钻石靴子
    - GOLDEN_BOOTS					# 金靴子
    - NETHERITE_BOOTS				# 下界合金靴子
    - LEATHER_LEGGINGS				# 皮革护腿
    - CHAINMAIL_LEGGINGS			# 锁链护腿
    - IRON_LEGGINGS					# 铁护腿
    - DIAMOND_LEGGINGS				# 钻石护腿
    - GOLDEN_LEGGINGS				# 金护腿
    - NETHERITE_LEGGINGS			# 下界合金护腿
    - LEATHER_HELMET				# 皮革头盔
    - CHAINMAIL_HELMET				# 锁链头盔
    - IRON_HELMET					# 铁头盔
    - DIAMOND_HELMET				# 钻石头盔
    - GOLDEN_HELMET					# 金头盔
    - NETHERITE_HELMET				# 下界合金头盔
    - TURTLE_HELMET					# 海龟壳
    - LEATHER_HORSE_ARMOR			# 皮革马铠
    - IRON_HORSE_ARMOR				# 铁马铠
    - GOLDEN_HORSE_ARMOR			# 金马铠
    - DIAMOND_HORSE_ARMOR			# 钻石马铠
    - WOLF_ARMOR					# 狼铠
tool-and-weapon-item:                     # 工具与武器
    - WOODEN_AXE				# 木斧
    - STONE_AXE					# 石斧
    - IRON_AXE					# 铁斧
    - DIAMOND_AXE				# 钻石斧
    - GOLDEN_AXE				# 金斧
    - NETHERITE_AXE				# 下界合金斧
    - WOODEN_PICKAXE			# 木镐
    - STONE_PICKAXE				# 石镐
    - IRON_PICKAXE				# 铁镐
    - DIAMOND_PICKAXE			# 钻石镐
    - GOLDEN_PICKAXE			# 金镐
    - NETHERITE_PICKAXE			# 下界合金镐
    - WOODEN_HOE				# 木锄
    - STONE_HOE					# 石锄
    - IRON_HOE					# 铁锄
    - DIAMOND_HOE				# 钻石锄
    - GOLDEN_HOE				# 金锄
    - NETHERITE_HOE				# 下界合金锄
    - WOODEN_SHOVEL				# 木锹
    - STONE_SHOVEL				# 石锹
    - IRON_SHOVEL				# 铁锹
    - DIAMOND_SHOVEL			# 钻石锹
    - GOLDEN_SHOVEL				# 金锹
    - NETHERITE_SHOVEL			# 下界合金锹
    - WOODEN_SWORD				# 木剑
    - STONE_SWORD				# 石剑
    - IRON_SWORD				# 铁剑
    - DIAMOND_SWORD				# 钻石剑
    - GOLDEN_SWORD				# 金剑
    - NETHERITE_SWORD			# 下界合金剑
    - MACE						# 重锤
    - TRIDENT					# 三叉戟
    - SHIELD					# 盾
    - CROSSBOW					# 弩
    - BOW						# 弓
cheap-block-item:                       # 廉价方块
    - OAK_PLANKS				# 橡木木板
    - SPRUCE_PLANKS				# 云杉木板
    - BIRCH_PLANKS				# 白桦木板
    - JUNGLE_PLANKS				# 丛林木板
    - ACACIA_PLANKS				# 金合欢木板
    - DARK_OAK_PLANKS			# 深色橡木木板
    - MANGROVE_PLANKS			# 红树木板
    - CHERRY_PLANKS				# 樱花木板
    - BAMBOO_PLANKS				# 竹板
    - PALE_OAK_PLANKS			# 苍白橡木木板
    - CRIMSON_PLANKS			# 绯红木板
    - WARPED_PLANKS				# 诡异木板
    - OAK_LEAVES				# 橡树树叶
    - SPRUCE_LEAVES				# 云杉树叶
    - BIRCH_LEAVES				# 白桦树叶
    - JUNGLE_LEAVES				# 丛林树叶
    - ACACIA_LEAVES				# 金合欢树叶
    - DARK_OAK_LEAVES			# 深色橡树树叶
    - MANGROVE_LEAVES			# 红树树叶
    - CHERRY_LEAVES				# 樱花树叶
    - AZALEA_LEAVES				# 杜鹃树叶
    - FLOWERING_AZALEA_LEAVES	# 盛开的杜鹃树叶
    - PALE_OAK_LEAVES			# 苍白橡树树叶
    - ANDESITE					# 安山岩
    - BASALT					# 玄武岩
    - DIORITE					# 闪长岩
    - GRANITE					# 花岗岩
    - DEEPSLATE					# 深板岩
    - COBBLED_DEEPSLATE			# 深板岩圆石
    - STONE						# 石头
    - COBBLEDSTONE				# 圆石
    - MOSSY_COBBLESTONE			# 苔石
    - SANDSTONE					# 砂岩
    - RED_SANDSTONE				# 红砂岩
    - SAND						# 沙子
    - RED_SAND					# 红沙
    - GRAVEL					# 沙砾
    - COARSE_DIRT				# 砂土
    - DIRT						# 泥土
    - MOSS_BLOCK				# 苔藓块
    - MUD						# 泥巴
    - NETHERRACK				# 下界岩
    - END_STONE					# 末地石

